/*================================================================================
  SEQUENCES AND TRIGGERS for AUTO-INCREMENT
  Oracle doesn't have auto-increment, so we create sequences and triggers
  Execute this script SECOND
================================================================================*/

-- Drop existing sequences
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_user';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_student';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_coach';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_nurse';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_healthprofile';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_fitnesslog';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_medicalrecord';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_goal';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_appointment';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_trainingplan';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_plandetail';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_coachreview';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create sequences
CREATE SEQUENCE seq_user START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_student START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_coach START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_nurse START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_healthprofile START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_fitnesslog START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_medicalrecord START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_goal START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_appointment START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_trainingplan START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_plandetail START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE seq_coachreview START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- Drop existing triggers
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_user_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_student_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_coach_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_nurse_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_healthprofile_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_fitnesslog_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_medicalrecord_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_goal_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_appointment_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_trainingplan_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_plandetail_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_coachreview_id';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create triggers for auto-increment
CREATE TRIGGER trg_user_id BEFORE INSERT ON "User" FOR EACH ROW
BEGIN
  IF :NEW.UserID IS NULL THEN
    SELECT seq_user.NEXTVAL INTO :NEW.UserID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_student_id BEFORE INSERT ON Student FOR EACH ROW
BEGIN
  IF :NEW.StudentID IS NULL THEN
    SELECT seq_student.NEXTVAL INTO :NEW.StudentID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_coach_id BEFORE INSERT ON Coach FOR EACH ROW
BEGIN
  IF :NEW.CoachID IS NULL THEN
    SELECT seq_coach.NEXTVAL INTO :NEW.CoachID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_nurse_id BEFORE INSERT ON Nurse FOR EACH ROW
BEGIN
  IF :NEW.NurseID IS NULL THEN
    SELECT seq_nurse.NEXTVAL INTO :NEW.NurseID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_healthprofile_id BEFORE INSERT ON HealthProfile FOR EACH ROW
BEGIN
  IF :NEW.ProfileID IS NULL THEN
    SELECT seq_healthprofile.NEXTVAL INTO :NEW.ProfileID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_fitnesslog_id BEFORE INSERT ON FitnessLog FOR EACH ROW
BEGIN
  IF :NEW.LogID IS NULL THEN
    SELECT seq_fitnesslog.NEXTVAL INTO :NEW.LogID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_medicalrecord_id BEFORE INSERT ON MedicalRecord FOR EACH ROW
BEGIN
  IF :NEW.RecordID IS NULL THEN
    SELECT seq_medicalrecord.NEXTVAL INTO :NEW.RecordID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_goal_id BEFORE INSERT ON Goal FOR EACH ROW
BEGIN
  IF :NEW.GoalID IS NULL THEN
    SELECT seq_goal.NEXTVAL INTO :NEW.GoalID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_appointment_id BEFORE INSERT ON Appointment FOR EACH ROW
BEGIN
  IF :NEW.AppointmentID IS NULL THEN
    SELECT seq_appointment.NEXTVAL INTO :NEW.AppointmentID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_trainingplan_id BEFORE INSERT ON TrainingPlan FOR EACH ROW
BEGIN
  IF :NEW.PlanID IS NULL THEN
    SELECT seq_trainingplan.NEXTVAL INTO :NEW.PlanID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_plandetail_id BEFORE INSERT ON PlanDetail FOR EACH ROW
BEGIN
  IF :NEW.DetailID IS NULL THEN
    SELECT seq_plandetail.NEXTVAL INTO :NEW.DetailID FROM dual;
  END IF;
END;
/

CREATE TRIGGER trg_coachreview_id BEFORE INSERT ON CoachFitnessReview FOR EACH ROW
BEGIN
  IF :NEW.ReviewID IS NULL THEN
    SELECT seq_coachreview.NEXTVAL INTO :NEW.ReviewID FROM dual;
  END IF;
END;
/

COMMIT;
